apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-injector-admin-role-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-ingress-injector-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ingress-injector-service-account
    namespace: {{ .Release.Namespace }}
